version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app

  # sempre que precisar parar os container rode o comando:
  # docker compose down --volumes

